version: '3.8'

services:
  master:
    build: .
    container_name: master_api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_CONNECTION_STRING: "redis://redis:6379"
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"
      RESULTS_DIR: "results"
      RESULTS_FILE_NAME: "cracked_passwords.json"
    volumes:
      - ./results:/app/results
    networks:
      - app_network

  minion:
    build: .
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_CONNECTION_STRING: "redis://redis:6379"
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"
    deploy:
      replicas: 5
    networks:
      - app_network

  result_processor:
    build: .
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_CONNECTION_STRING: "redis://redis:6379"
      RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@rabbitmq:5672/"
      RESULTS_DIR: "results"
      RESULTS_FILE_NAME: "cracked_passwords.json"
    deploy:
      replicas: 2
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=500m"
  rabbitmq_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=500m"